name: Build for Windows 98

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Open Watcom
        uses: open-watcom/setup-watcom@v0
        with:
          version: "2.0"
          target: "nt"

      - name: Compile for Windows 98
        run: |
          wcl386 -l=nt -os -i=./vendor \
          -d__inline__= \
          -d_HAS_TIMESPEC \
          -d_WIN32 \
          main.c celq.c vendor/wasi.c vendor/win32.c -fe=celq.exe

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celq-win98
          path: celq.exe