name: Build for Windows 98 w/ MinGW
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Install MinGW
        run: |
          sudo apt-get update
          sudo apt-get install -y mingw-w64
      
      - name: Compile for Windows 98
        run: |
          i686-w64-mingw32-gcc \
            -o celq.exe \
            -O2 \
            -I./vendor \
            -D__inline__= \
            -D_WIN32 \
            -D_X86_ \
            -D_MSC_VER=1000 \
            -DHAS_UNISTD=0 \
            -DHAS_TIMESPEC=1 \
            -D_WIN32_WINNT=0x0410 \
            -DWINVER=0x0410 \
            -static-libgcc \
            -static-libstdc++ \
            main.c celq.c vendor/wasi.c vendor/win32.c \
            -lkernel32 -luser32 -lgdi32 -lwsock32
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: celq-win98
          path: celq.exe